theme = "blowfish"
baseURL = "https://scholion.thluiz.com/"
defaultContentLanguage = "pt-br"
languageCode = "pt-BR"
title = "Scholion"

enableGitInfo = true
enableRobotsTXT = true
enableEmoji = true
summaryLength = 30

buildDrafts = false
buildFuture = false

[pagination]
  pagerSize = 40

[taxonomies]
  tag = "tags"
  source = "sources"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[related]
  threshold = 80
  includeNewer = true
  toLower = true

  [[related.indices]]
    name = "tags"
    weight = 100

  [[related.indices]]
    name = "date"
    weight = 5

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
