[[main]]
  name = "Notas"
  pageRef = "notes"
  weight = 10

[[main]]
  name = "Citações"
  pageRef = "quotes"
  weight = 12

[[main]]
  name = "Fontes"
  pageRef = "sources"
  weight = 15

[[main]]
  name = "Tags"
  pageRef = "tags"
  weight = 20
